// <auto-generated />
using System;
using FitDash.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitDash.Migrations
{
    [DbContext(typeof(FitDashContext))]
    [Migration("20241208144341_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitDash.Domain.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<float?>("Carbs")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Fats")
                        .HasColumnType("real");

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Proteins")
                        .HasColumnType("real");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Meal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 400f,
                            Carbs = 50f,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6327),
                            DateUpdated = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6327),
                            Fats = 10f,
                            MealDate = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6326),
                            MealName = "Breakfast",
                            Proteins = 25f,
                            UpdatedBy = "System",
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            Calories = 600f,
                            Carbs = 70f,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6330),
                            DateUpdated = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6330),
                            Fats = 15f,
                            MealDate = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6330),
                            MealName = "Lunch",
                            Proteins = 40f,
                            UpdatedBy = "System",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FitDash.Domain.ProgressTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("BMI")
                        .HasColumnType("real");

                    b.Property<float?>("BodyFatPercentage")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("ProgressTracker");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BMI = 24.5f,
                            BodyFatPercentage = 20f,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRecorded = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6443),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1,
                            Weight = 70f
                        },
                        new
                        {
                            Id = 2,
                            BMI = 22f,
                            BodyFatPercentage = 18f,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRecorded = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6445),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserID = 2,
                            Weight = 60f
                        });
                });

            modelBuilder.Entity("FitDash.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityLevel = "Active",
                            DateCreated = new DateTime(2024, 12, 8, 22, 43, 41, 250, DateTimeKind.Local).AddTicks(5979),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 8, 22, 43, 41, 250, DateTimeKind.Local).AddTicks(5993),
                            Email = "johndoe@example.com",
                            Gender = "Male",
                            Height = 175f,
                            Name = "John Doe",
                            Password = "P@ssword1",
                            Weight = 70f
                        },
                        new
                        {
                            Id = 2,
                            ActivityLevel = "Active",
                            DateCreated = new DateTime(2024, 12, 8, 22, 43, 41, 250, DateTimeKind.Local).AddTicks(5996),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2024, 12, 8, 22, 43, 41, 250, DateTimeKind.Local).AddTicks(5997),
                            Email = "janedoe@example.com",
                            Gender = "Male",
                            Height = 175f,
                            Name = "Jane Doe",
                            Password = "P@ssword1",
                            Weight = 70f
                        });
                });

            modelBuilder.Entity("FitDash.Domain.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("CaloriesBurned")
                        .HasColumnType("real");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkoutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Workout");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesBurned = 300f,
                            DateCreated = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6207),
                            DateUpdated = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6208),
                            Duration = 30,
                            UserID = 1,
                            WorkoutDate = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6207),
                            WorkoutName = "Cardio"
                        },
                        new
                        {
                            Id = 2,
                            CaloriesBurned = 400f,
                            DateCreated = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6210),
                            DateUpdated = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6211),
                            Duration = 45,
                            UserID = 2,
                            WorkoutDate = new DateTime(2024, 12, 8, 14, 43, 41, 250, DateTimeKind.Utc).AddTicks(6210),
                            WorkoutName = "Strength Training"
                        });
                });

            modelBuilder.Entity("FitDash.Domain.Meal", b =>
                {
                    b.HasOne("FitDash.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitDash.Domain.ProgressTracker", b =>
                {
                    b.HasOne("FitDash.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitDash.Domain.Workout", b =>
                {
                    b.HasOne("FitDash.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
